### ISSUE TITLE
[script remover] - make exception for evoadmin.io

### ISSUE THREAD

**Issue by Talyna** [Nexus-Websites/Heimdall#4]

**Comment by supersonic1999** [comment]
`// ==UserScript==
// @name         Script Remover
// @run-at document-start
// @match        https://*/*
// @match        *
// @match        http://*/*
// ==/UserScript==

if(location.hostname != 'us.evoadmin.io' &&
	 location.hostname != 'eu.evoadmin.io' &&
	 location.hostname != 'sauroneu.evoadmin.io' &&
	 location.hostname != 'sauronus.evoadmin.io'){
	document.addEventListener("beforescriptexecute", function(script) {
		script.preventDefault();
		script.stopPropagation();
		script.target.remove();
	});
}`
